fable-hub/Feliz

src/Properties.fs
=> make styleList and styleWhen overloads of style

src/Properties.fs
Closes #41
WIP, some props are yet to be added.
=> Add ARIA props

Feliz/Properties.fs
* Added ``` `code` ``` formatting
* Constrained line length
* Added docs for values
=> Improve formatting of textAnchor

package-lock.json, package.json
This adds pigeon-maps to the package.json to fix the build.
=> Build fix - missing pigeon-maps

docs/Recharts/BarCharts/MixBarChart.fs, public/Recharts/BarCharts/MixBarChart.md
Add legend and correct dataKeys to match Recharts example.
=> Add legend and correct dataKeys

Feliz/Properties.fs, docs/App.fs
=> Rename withType -> type'

Feliz/Html.fs
=> Added thead element

Feliz/Properties.fs
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
=> Add autoCapitalize prop

Feliz.ElmishComponents/Components.fs
This is the smallest contribution ever: a single keystroke!
=> Fixed misspelled module "ElmishComponentExtensions".

public/Feliz/Syntax.md
=> Clarify prop vs. element list

Feliz/Properties.fs
=> Add missed html props

Feliz/Properties.fs
I believe this will fix https://github.com/Zaid-Ajaj/Feliz/issues/153
=> maxlength -> maxLength

Feliz/Properties.fs
Added missing `allow` attribute for `iframe` elements for #174.
=> Add iframe allow attribute

Feliz/React.fs, tests/Tests.fs
=> Refactor memo and functionComponent overloads

Feliz.UseDeferred/Feliz.UseDeferred.fsproj, Feliz.UseDeferred/UseDeferred.fs, build.fsx, docs/App.fs, docs/App.fsproj, docs/Urls.fs, public/Feliz.UseDeferred/Index.md
This is an initial API design for using the `Deferred<'T>` type in a nice way that works with React function components and follows hook rules. It exposes two methods: 
- `React.useDeferred`
- `React.useDeferredCallback` 
I have included two live examples in the docs of they should work 
@Shmew What do you think of this API, it is a bit different than the one we discussed before but covers quite a lot of ground for many use cases.
=> Initial implementation of Feliz.UseDeferred

Feliz.ElmishComponents/Components.fs, Feliz.UseElmish/Feliz.UseElmish.fsproj, Feliz.UseElmish/UseElmish.fs, build.fsx, docs/App.fs, docs/App.fsproj, docs/Urls.fs, docs/UseDeferredExamples.fs, docs/UseElmishExamples.fs, public/Feliz.UseElmish/Index.md
Thanks to @Shmew of course, we can use the elmish model for managing state inside React components and be able to make use and combine it with other powerful React hooks!
=> Feliz.UseElmish: The Final Form

Feliz.UseElmish/UseElmish.fs
I realized a snippet of code wasn't being used in the implementation for the elmish dispatch loop.
=> Remove unnecessary code

Feliz/React.fs
=> Fix displayName for memoized components

Feliz.RoughViz/BarChart.fs, Feliz.RoughViz/Feliz.RoughViz.fsproj, Feliz.RoughViz/RoughViz.fs, Feliz.RoughViz/createChart.js, build.fsx, docs/App.fs, docs/App.fsproj, docs/Urls.fs, package-lock.json, package.json, public/RoughViz/Index.md
Something fun to play with :smile: Also a nice example to showcase a Feliz binding for a library that works with the DOM directly and how to build a React component out of it.
=> Feliz.RoughViz v1.0 with docs and dynamic examples

Feliz.Template/Content/App.sln
Make package.json and webpack config 1-click
accessible when using Rider.
=> Added Solution Items to Template

Feliz.UseDeferred/UseDeferred.fs
Using a closure might not work because React seems to cache the `operation` function. So in my case the following example prints different values to the console:
```fsharp
let (sendOrderState, setSendOrderState) = React.useState(Deferred.HasNotStartedYet)
let (authKey, setAuthKey) = React.useState(Deferred.HasNotStartedYet)
// ...
let startSendOrder =
React.useDeferredCallback(
(fun () -> async {
printfn "%O" authKey
// TODO use auth key
}),
setSendOrderState
)
// Chain two `Deferred`s together - if `authKey` is resolved and `sendOrderState` hasn't started, start `sendOrderState`
if Deferred.resolved authKey && Deferred.hasNotStartedYet sendOrderState then
printfn "%O" authKey
startSendOrder ()
```
This PR enables passing `authKey` as parameter to `startSendOrder` which obviously results …
=> Allow passing parameter to start function of `useDeferredCallback`

Feliz.UseMediaQuery/UseMediaQuery.fs
Moved the UseMediaQuery hook to the old version as
a workaround for missing functionality on Safari.
=> Bugfix: Safari UseMediaQuery

public/Feliz/ProjectTemplate.md
When I cloned the repo, and was looking for instructions to run the app I couldn't find any in the documentation. Added this section for people not familiar with `npm`.
If these instructions are somewhere that I missed, just close this PR :)
=> Added Instructions to Run Application

Feliz/Length.fs
Hello Zaid, I'm really not sure if this is the best place to put this function to support css calculations and I guess that providing the value only as a string is not a safe thing to do, but creating some kind of dsl for it would be so much more complex from my point o view. 
If you have any ideas/suggestions how to implement it better feel free to suggest them :)
=> Added suport for calculated length values

Feliz/React.fs, tests/Tests.fs
Adds the following `React.createDisposable` overloads:
- `[<ParamArray>] IDisposable`
- `[<ParamArray>] IDisposable option`
- `[<ParamArray>] IRefValue<IDisposable>`
- `[<ParamArray>] IRefValue<IDisposable option>`
This lets us turn code like this:
```fsharp
React.createDisposable(fun () ->
oneDis.current |> Option.iter(fun o -> o.Dispose())
twoDis.current |> Option.iter(fun o -> o.Dispose())
threeDis.current |> Option.iter(fun o -> o.Dispose())
fourDis.current |> Option.iter(fun o -> o.Dispose())
)
```
into
```fsharp
React.createDisposable(oneDis, twoDis, threeDis, fourDis)
```
=> Add IDisposable overloads for React.createDisposable

Feliz/Length.fs
Sorry, I forgot to add the inline to the member definition
=> add inline to calc

Feliz/Properties.fs
=> Fix prop.rel and prop.result, add missing rel overloads.

public/Feliz/ElmishComponents.md
Based on this https://github.com/Zaid-Ajaj/Feliz/issues/263#issuecomment-705370349 I would put a note in official docs
=> ElmishComponents deprecation note

Feliz.Recharts/Area.fs, Feliz.Recharts/AreaChart.fs, Feliz.Recharts/Bar.fs, Feliz.Recharts/BarChart.fs, Feliz.Recharts/Brush.fs, Feliz.Recharts/CartesianGrid.fs, Feliz.Recharts/Cell.fs, Feliz.Recharts/ComposedChart.fs, Feliz.Recharts/Feliz.Recharts.fsproj, Feliz.Recharts/Interop.fs, Feliz.Recharts/Line.fs, Feliz.Recharts/LineChart.fs, Feliz.Recharts/Pie.fs, Feliz.Recharts/PieChart.fs, Feliz.Recharts/Recharts.fs, Feliz.Recharts/ReferenceArea.fs, Feliz.Recharts/ReferenceDot.fs, Feliz.Recharts/ReferenceLine.fs, Feliz.Recharts/ResponsiveContainer.fs, Feliz.Recharts/Types.fs, Feliz.Recharts/XAxis.fs, Feliz.Recharts/YAxis.fs
=> Use specialized attribute types for charts

Feliz/BorderStyle.fs, build.fsx
No actual code changes
* Updated links to represent the corresponding border style
* Updated hardcoded npm to the configured npmTool to support yarn
=> Minor fixes to documentation and build script

Feliz/Styles.fs
It seems box-sizing and resize were not yet supported.
=> Add box-sizing and resize styles

Feliz.Recharts/Feliz.Recharts.fsproj, Feliz.Recharts/Interop.fs, Feliz.Recharts/Line.fs, Feliz.Recharts/Recharts.fs, Feliz.Recharts/ScatterChart.fs, Feliz.Recharts/Tooltip.fs, Feliz.Recharts/YAxis.fs
A lot of Rechart api is missing. I added scatterchart and tooltip and some extra attrs for line and yAxis.
=> Added scatterchart and tooltip

Feliz.Template/Content/package-lock.json
=> Revert "Bump elliptic from 6.5.3 to 6.5.4 in /Feliz.Template/Content"

Feliz.Recharts/XAxis.fs, Feliz.Recharts/YAxis.fs
Some more properties that will let me work around https://github.com/recharts/recharts/issues/2027.
=> Add width and height to Recharts X, Y axes

Feliz/Properties.fs
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-scope
=> Add scope property for th Html element

Feliz/Properties.fs
React was complaining this is wrong.
Also added a corrected version.
Not sure how you want to handle removing wrong/old versions.
=> Fixed React complaining about onDblClick being wrong

Feliz/Svg.fs
I pretty much copied this from Pie.fs in Feliz.Recharts
=> added % options for x and y properties in SVG

Feliz.Recharts/Cell.fs
Hi @Zaid-Ajaj,
I added a binding for the onclick event for Rechart Cell elements.
=> add rechart cell onclick binding

Feliz/UsingJsx.md
Thanks for your work on Feliz!
=> typo comnponent -> component

Feliz/Styles.fs
Options to specify different borderRadius for individual corners
=> style.borderRadius(1, 2, 3, 4)

Feliz/Properties.fs
=> Fixed prop.span naming

Feliz/Svg.fs
=> Updated SVG Attribute:

Feliz.CompilerPlugins/ReactComponent.fs
=> Fix react memo import

Feliz/Styles.fs
Added properties for text orientation.
=> Added text-orientation property

Feliz/StyleTypes.fs, Feliz/Styles.fs, Feliz/TransformOrigin.fs
Implemented a sensible API for transformOrigin that incorporates the entire spec
(Ref: https://developer.mozilla.org/de/docs/Web/CSS/transform-origin)
=> Add Transform-Origin to Style module

Feliz/ReactDOM.fs, Feliz/ReactTypes.fs, README.md, tests/Utilities.fs
Since react 18, ReactDOM.render is deprecated. I suggest to update Feliz.
=> Change render to createRoot

Feliz/Properties.fs, Feliz/Svg.fs
A little spell correction
ping @Zaid-Ajaj
=> fix: little spell correction

Feliz.Template/Content/.config/dotnet-tools.json
This fixes the error with dotnet 7 and also the error with the hooks I reported here: https://github.com/Zaid-Ajaj/Feliz/issues/535#issuecomment-1441418947
=> Update Fable dotnet tool version

Feliz.Template/Content/.npmrc, Feliz.Template/Content/package.json
=> Enforce Node.js version in Feliz.Template

Feliz.CompilerPlugins/AstUtils.fs, Feliz.CompilerPlugins/ReactComponent.fs
=> Set displayName for ReactMemoComponent

Feliz/Styles.fs
#584 First attempt at pull request as suggested.
=> Implement overflow-anchor style property.

Feliz/Length.fs
Add min, max, minmax, minContent, fitContent, maxContent and custom length options.
This should help making tricky css grid code a bit nicer.
=> Add more CssUnit options

Feliz/Styles.fs
Add styles:
- scrollbarGutter
- scrollbarWidth
- scrollbarColor
- scrollSnapAlign
- scrollSnapType
=> Add more scroll and scrollbar styles

Feliz/Styles.fs
Hi,
I did not find any contributing policy and this is my first time contributing to this project – I hope it is ok to just open a PR without an issue etc. Please advice, should I be missing something!
This PR adds the missing CCS-test-3 value `break-spaces` for the `white-space` property.
=> Add CSS-text-3 value of `break-spaces` for the `white-space` property.

Feliz/Styles.fs
Add style properties:
- margin-block
- margin-block-start
- margin-block-end
- padding-block
- padding-block-start
- padding-block-end
- margin-inline
- margin-inline-start
- margin-inline-end
- padding-inline
- padding-inline-start
- padding-inline-end
As well as the necessary overloads
=> Add margin and padding block and inline style properties
